In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import re
import nltk
import torch
from nltk.corpus import stopwords
from nltk.stem import SnowballStemmer
from collections import Counter
from wordcloud import WordCloud
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.svm import LinearSVC
from sklearn.metrics import accuracy_score, classification_report
from Scripts.DataManager.GraphConstructor.SentenceGraphConstructor import SentenceGraphConstructor

stop_words = set(stopwords.words('english'))
stemmer = SnowballStemmer('english')
from Scripts.Configs.ConfigClass import Config
config = Config(r'C:\Users\fardin\Projects\ColorIntelligence')
from torch_geometric.data import Data
from torch_geometric.utils import to_networkx
import networkx as nx

In [2]:
train_df = pd.read_csv(r'C:\Users\fardin\Projects\ColorIntelligence\data\Amazon-Review\train_sm.csv')
test_df = pd.read_csv(r'C:\Users\fardin\Projects\ColorIntelligence\data\Amazon-Review\test_sm.csv')

In [3]:
train_df.columns = ['Polarity', 'Title', 'Review']
test_df.columns = ['Polarity', 'Title', 'Review']

In [4]:
train_df = train_df[['Polarity', 'Review']]
test_df = test_df[['Polarity', 'Review']]

In [6]:
# start_time = time.time()
# graph_const = CoOccurrenceGraphConstructor(train_df['Review'], 'AmazonReview', config, lazy_construction=True,  load_preprocessed_data=True, naming_prepend='graph')
# print(f'execution time in second: {time.time() - start_time}')
graph_const = SentenceGraphConstructor(train_df['Review'][:10], r'data\GraphData\Sentences', config, lazy_construction=False, naming_prepend='graph', load_preprocessed_data=False , use_general_node=False,use_compression=True)
# graph = graph_const.to_graph(train_df['Review'][0])
graph_const.setup(load_preprocessed_data=False)


i: 0


In [7]:
graph_const.save_all_data_compressed()
graph_const.load_all_data_comppressed()

filename: C:\Users\fardin\Projects\ColorIntelligence\data\GraphData\Sentences\graph_var.txt
data loading 0


In [9]:

print(graph_const.get_first()['word', 'word_sentence', 'sentence'].edge_index)

tensor([[  0,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,  13,
          14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,  26,  27,
          28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,  39,  40,  41,
          42,  43,  44,  45,  46,  47,  48,  49,  50,  51,  52,  53,  54,  55,
          56,  57,  58,  59,  60,  61,  62,  63,  64,  65,  66,  67,  68,  69,
          70,  71,  72,  73,  74,  75,  76,  77,  78,  79,  80,  81,  82,  83,
          84,  85,  86,  87,  88,  89,  90,  91,  92,  93,  94,  95,  96,  97,
          98,  99, 100, 101, 102, 103],
        [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
           0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
           0,   0,   0,   1,   1,   1,   1,   1,   1,   1,   1,   1,   1,   1,
           2,   2,   2,   2,   2,   2,   2,   2,   2,   2,   2,   2,   2,   2,
           2,   2,   2,   2,   2,   2,   2,   2,   3,   3,   3,   3,   3,   3,
           3

In [ ]:

graph_const = SentenceGraphConstructor(train_df['Review'][:10], r'data\GraphData\Sequential', config, lazy_construction=False, naming_prepend='graph', load_preprocessed_data=False , use_general_node=True , use_compression=True)

graph_const.setup(load_preprocessed_data=False)

i: 0


In [ ]:
graph_const.save_all_data_compressed()
graph_const.load_all_data_comppressed()

filename: C:\Users\fardin\Projects\ColorIntelligence\data\GraphData\Sequential\graph_var.txt
data loading 0


In [ ]:
print(graph_const.get_first()['word'].x)
print(graph_const.get_first()['sentence'].x)
print(graph_const.get_first()['word', 'word_sentence', 'sentence'].edge_index)
print(graph_const.get_first()['word', 'word_sentence', 'sentence'].edge_attr)

tensor([[ -1.8607,   0.1580,  -4.1425,  ...,   7.9379, -11.5700,   4.3334],
        [ -9.3526,   3.6551,  -3.2571,  ...,  -5.4425,  -0.4818,  11.2790],
        [  2.5446,  -1.0674,   3.9179,  ...,   0.3310,  -4.3464,  -3.4984],
        ...,
        [  1.9537,   2.2470,  -6.4141,  ...,   1.6256,  -4.4401,   0.8307],
        [ -1.3229,  -0.9106,  -0.1730,  ...,  -0.5912,  -0.5681,  -0.8500],
        [ -0.0765,  -4.6896,  -4.0431,  ...,   1.3040,  -0.5270,  -1.3622]])
tensor([[-1.7032,  1.7425, -1.6102,  ...,  0.6357, -5.1856,  2.3915],
        [ 0.4991,  1.3327, -1.8460,  ...,  0.2311, -2.5590, -0.3960],
        [-0.9843,  2.5637, -2.0936,  ...,  0.4817, -5.9182,  3.8722],
        [-1.4629,  2.0345, -2.9621,  ...,  0.6594, -3.8472,  1.8625]])
tensor([[  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
           0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
           0,   0,   0,  31,  31,  31,  31,  31,  31,  31,  31,  31,  31,  31,
          42

In [ ]:

graph_const = SentenceGraphConstructor(train_df['Review'][:10], r'data\GraphData\Sequential', config, lazy_construction=False,
                                       naming_prepend='graph', load_preprocessed_data=False, use_general_node=True, use_compression=True)

graph_const.setup(load_preprocessed_data=False)

i: 0


In [ ]:
graph_const.save_all_data_compressed()
graph_const.load_all_data_comppressed()

filename: C:\Users\fardin\Projects\ColorIntelligence\data\GraphData\Sequential\graph_var.txt
data loading 0


In [ ]:
print(graph_const.get_first()['word'].x)
print(graph_const.get_first()['general'].x)
print(graph_const.get_first()['sentence', 'sentence_general', 'general'].edge_index)
print(graph_const.get_first()['sentence', 'sentence_general', 'general'].edge_attr)

tensor([[ -1.8607,   0.1580,  -4.1425,  ...,   7.9379, -11.5700,   4.3334],
        [ -9.3526,   3.6551,  -3.2571,  ...,  -5.4425,  -0.4818,  11.2790],
        [  2.5446,  -1.0674,   3.9179,  ...,   0.3310,  -4.3464,  -3.4984],
        ...,
        [  1.9537,   2.2470,  -6.4141,  ...,   1.6256,  -4.4401,   0.8307],
        [ -1.3229,  -0.9106,  -0.1730,  ...,  -0.5912,  -0.5681,  -0.8500],
        [ -0.0765,  -4.6896,  -4.0431,  ...,   1.3040,  -0.5270,  -1.3622]])
tensor([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
         0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
         0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
         0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
         0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
     