In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import re
import nltk
import torch
from nltk.corpus import stopwords
from nltk.stem import SnowballStemmer
from collections import Counter
from wordcloud import WordCloud
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.svm import LinearSVC
from sklearn.metrics import accuracy_score, classification_report
from Scripts.DataManager.GraphConstructor.TagDepTokenGraphConstructor import TagDepTokenGraphConstructor

stop_words = set(stopwords.words('english'))
stemmer = SnowballStemmer('english')
from Scripts.Configs.ConfigClass import Config
config = Config(r'C:\Users\fardin\Projects\ColorIntelligence')
from torch_geometric.data import Data
from torch_geometric.utils import to_networkx
import networkx as nx

In [2]:
train_df = pd.read_csv(r'C:\Users\fardin\Projects\ColorIntelligence\data\Amazon-Review\train_sm.csv')
test_df = pd.read_csv(r'C:\Users\fardin\Projects\ColorIntelligence\data\Amazon-Review\test_sm.csv')

In [3]:
train_df.columns = ['Polarity', 'Title', 'Review']
test_df.columns = ['Polarity', 'Title', 'Review']

In [4]:
train_df = train_df[['Polarity', 'Review']]
test_df = test_df[['Polarity', 'Review']]

In [5]:

graph_const = TagDepTokenGraphConstructor(train_df['Review'][:10], r'data\GraphData\Dependency', config, lazy_construction=False, naming_prepend='graph', load_preprocessed_data=False, use_sentence_nodes=False, use_general_node=False , use_compression=True)
graph_const.setup(load_preprocessed_data=False)

i: 0
tags length : 50
tags length : 50
tags length : 50
tags length : 50
tags length : 50
tags length : 50
tags length : 50
tags length : 50
tags length : 50
tags length : 50


In [6]:
graph_const.save_all_data_compressed()
graph_const.load_all_data_comppressed()

filename: C:\Users\fardin\Projects\ColorIntelligence\data\GraphData\Dependency\graph_var.txt
data loading 0
tags length : 50
tags length : 50
tags length : 50
tags length : 50
tags length : 50
tags length : 50
tags length : 50
tags length : 50
tags length : 50
tags length : 50


In [7]:
print(graph_const.get_first()['word'].x)
print(graph_const.get_first()['tag'].x.shape)
print(graph_const.get_first()['word', 'word_dep', 'dep'].edge_index)
print(graph_const.get_first()['word', 'word_dep', 'dep'].edge_attr)

tensor([[ -1.8607,   0.1580,  -4.1425,  ...,   7.9379, -11.5700,   4.3334],
        [ -9.3526,   3.6551,  -3.2571,  ...,  -5.4425,  -0.4818,  11.2790],
        [  2.5446,  -1.0674,   3.9179,  ...,   0.3310,  -4.3464,  -3.4984],
        ...,
        [  1.9537,   2.2470,  -6.4141,  ...,   1.6256,  -4.4401,   0.8307],
        [ -1.3229,  -0.9106,  -0.1730,  ...,  -0.5912,  -0.5681,  -0.8500],
        [ -0.0765,  -4.6896,  -4.0431,  ...,   1.3040,  -0.5270,  -1.3622]])
torch.Size([50, 50])
tensor([[  2,   2,   4,   2,   4,   5,   6,  10,  10,   7,  15,  15,  15,  15,
          10,  10,   2,  19,   2,  23,  23,  23,  19,  25,  23,  27,  25,  29,
          27,  19,  35,  31,  34,  32,  37,  40,  37,  40,  35,  35,  43,  44,
          44,  44,  50,  50,  50,  44,  50,  51,  50,  53,  54,  50,  58,  60,
          60,  50,  62,  60,  50,  66,  66,  69,  66,  67,  71,  69,  74,  74,
          69,  69,  69,  80,  80,  80,  91,  82,  80,  84,  82,  82,  88,  88,
          85,  91,  91,  69,  94,  

In [8]:
print(graph_const.get_first()['word'].x)
print(graph_const.get_first()['tag'].x)
print(graph_const.get_first()['word', 'word_tag', 'tag'].edge_index)
print(graph_const.get_first()['word', 'word_tag', 'tag'].edge_attr)

tensor([[ -1.8607,   0.1580,  -4.1425,  ...,   7.9379, -11.5700,   4.3334],
        [ -9.3526,   3.6551,  -3.2571,  ...,  -5.4425,  -0.4818,  11.2790],
        [  2.5446,  -1.0674,   3.9179,  ...,   0.3310,  -4.3464,  -3.4984],
        ...,
        [  1.9537,   2.2470,  -6.4141,  ...,   1.6256,  -4.4401,   0.8307],
        [ -1.3229,  -0.9106,  -0.1730,  ...,  -0.5912,  -0.5681,  -0.8500],
        [ -0.0765,  -4.6896,  -4.0431,  ...,   1.3040,  -0.5270,  -1.3622]])
tensor([[0., 0., 0.,  ..., 0., 0., 0.],
        [0., 0., 0.,  ..., 0., 0., 0.],
        [0., 0., 0.,  ..., 0., 0., 0.],
        ...,
        [0., 0., 0.,  ..., 0., 0., 0.],
        [0., 0., 0.,  ..., 0., 0., 0.],
        [0., 0., 0.,  ..., 0., 0., 0.]])
tensor([[  0,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,  13,
          14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,  26,  27,
          28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,  39,  40,  41,
          42,  43,  44,  45,  46,  47, 

In [9]:
graph_const = TagDepTokenGraphConstructor(train_df['Review'][:10], r'data\GraphData\Dependency', config, lazy_construction=False,
                                          naming_prepend='graph', load_preprocessed_data=False, use_sentence_nodes=False, use_compression=True,use_general_node=True)
graph_const.setup(load_preprocessed_data=False)

i: 0


In [10]:
graph_const.save_all_data_compressed()
graph_const.load_all_data_comppressed()

filename: C:\Users\fardin\Projects\ColorIntelligence\data\GraphData\Dependency\graph_var.txt
data loading 0


In [11]:
print(graph_const.get_first()['word'].x)
print(graph_const.get_first()['general'].x)
print(graph_const.get_first()['word', 'word_general', 'general'].edge_index)
print(graph_const.get_first()['word', 'word_general', 'general'].edge_attr)

tensor([[ -1.8607,   0.1580,  -4.1425,  ...,   7.9379, -11.5700,   4.3334],
        [ -9.3526,   3.6551,  -3.2571,  ...,  -5.4425,  -0.4818,  11.2790],
        [  2.5446,  -1.0674,   3.9179,  ...,   0.3310,  -4.3464,  -3.4984],
        ...,
        [  1.9537,   2.2470,  -6.4141,  ...,   1.6256,  -4.4401,   0.8307],
        [ -1.3229,  -0.9106,  -0.1730,  ...,  -0.5912,  -0.5681,  -0.8500],
        [ -0.0765,  -4.6896,  -4.0431,  ...,   1.3040,  -0.5270,  -1.3622]])
tensor([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
         0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
         0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
         0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
         0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
     

In [12]:
graph_const = TagDepTokenGraphConstructor(train_df['Review'][:10], r'data\GraphData\Dependency', config, lazy_construction=False,
                                          naming_prepend='graph', load_preprocessed_data=False, use_sentence_nodes=True, use_compression=True, use_general_node=False)
graph_const.setup(load_preprocessed_data=False)

i: 0


c:\Users\fardin\Projects\ColorIntelligence\Scripts\DataManager\GraphConstructor\TagDepTokenGraphConstructor.py:102: UserWarning: Creating a tensor from a list of numpy.ndarrays is extremely slow. Please consider converting the list to a single numpy.ndarray with numpy.array() before converting to a tensor. (Triggered internally at ..\torch\csrc\utils\tensor_new.cpp:264.)
  data['sentence'].x = torch.tensor(sentence_embeddings, dtype=torch.float32)


In [13]:
graph_const.save_all_data_compressed()
graph_const.load_all_data_comppressed()

filename: C:\Users\fardin\Projects\ColorIntelligence\data\GraphData\Dependency\graph_var.txt
data loading 0


In [14]:
print(graph_const.get_first()['word'].x)
print(graph_const.get_first()['sentence'].x)
print(graph_const.get_first()['word', 'word_sentence', 'sentence'].edge_index)
print(graph_const.get_first()['word', 'word_sentence', 'sentence'].edge_attr)

tensor([[ -1.8607,   0.1580,  -4.1425,  ...,   7.9379, -11.5700,   4.3334],
        [ -9.3526,   3.6551,  -3.2571,  ...,  -5.4425,  -0.4818,  11.2790],
        [  2.5446,  -1.0674,   3.9179,  ...,   0.3310,  -4.3464,  -3.4984],
        ...,
        [  1.9537,   2.2470,  -6.4141,  ...,   1.6256,  -4.4401,   0.8307],
        [ -1.3229,  -0.9106,  -0.1730,  ...,  -0.5912,  -0.5681,  -0.8500],
        [ -0.0765,  -4.6896,  -4.0431,  ...,   1.3040,  -0.5270,  -1.3622]])
tensor([[-1.7032,  1.7425, -1.6102,  ...,  0.6357, -5.1856,  2.3915],
        [ 0.4991,  1.3327, -1.8460,  ...,  0.2311, -2.5590, -0.3960],
        [-0.9843,  2.5637, -2.0936,  ...,  0.4817, -5.9182,  3.8722],
        [-1.4629,  2.0345, -2.9621,  ...,  0.6594, -3.8472,  1.8625]])
tensor([[  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
           0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
           0,   0,   0,  31,  31,  31,  31,  31,  31,  31,  31,  31,  31,  31,
          42

In [15]:
graph_const = TagDepTokenGraphConstructor(train_df['Review'][:10], r'data\GraphData\Dependency', config, lazy_construction=False,
                                          naming_prepend='graph', load_preprocessed_data=False, use_sentence_nodes=True, use_compression=True, use_general_node=True)
graph_const.setup(load_preprocessed_data=False)

i: 0


In [18]:
graph_const.save_all_data_compressed()
graph_const.load_all_data_comppressed()

filename: C:\Users\fardin\Projects\ColorIntelligence\data\GraphData\Dependency\graph_var.txt
data loading 0


In [19]:
print(graph_const.get_first()['word'].x)
print(graph_const.get_first()['sentence'].x)
print(graph_const.get_first()['general'].x)
print(graph_const.get_first()['sentence', 'sentence_general', 'general'].edge_index)
print(graph_const.get_first()['word', 'word_sentence', 'sentence'].edge_index)
print(graph_const.get_first()['sentence', 'sentence_general', 'general'].edge_attr)
print(graph_const.get_first()['word', 'word_sentence', 'sentence'].edge_attr)

tensor([[ -1.8607,   0.1580,  -4.1425,  ...,   7.9379, -11.5700,   4.3334],
        [ -9.3526,   3.6551,  -3.2571,  ...,  -5.4425,  -0.4818,  11.2790],
        [  2.5446,  -1.0674,   3.9179,  ...,   0.3310,  -4.3464,  -3.4984],
        ...,
        [  1.9537,   2.2470,  -6.4141,  ...,   1.6256,  -4.4401,   0.8307],
        [ -1.3229,  -0.9106,  -0.1730,  ...,  -0.5912,  -0.5681,  -0.8500],
        [ -0.0765,  -4.6896,  -4.0431,  ...,   1.3040,  -0.5270,  -1.3622]])
tensor([[-1.7032,  1.7425, -1.6102,  ...,  0.6357, -5.1856,  2.3915],
        [ 0.4991,  1.3327, -1.8460,  ...,  0.2311, -2.5590, -0.3960],
        [-0.9843,  2.5637, -2.0936,  ...,  0.4817, -5.9182,  3.8722],
        [-1.4629,  2.0345, -2.9621,  ...,  0.6594, -3.8472,  1.8625]])
tensor([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
         0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
         0., 0., 0., 0., 0., 0., 0., 0.